### ISSUE TITLE
To'g'irlanishi kerak bo'gan kamchiliklar

### ISSUE THREAD

**Issue by musmon** [Muhammadboburshoh/a-fuzzbuzz#1]
![image](https://user-images.githubusercontent.com/71978297/98640506-f1bac280-234b-11eb-8dd7-5ad20a5897ec.png)

Required olib tashlansa pustoy probelni ham o'tqazib yuboryapti))

**Comment by Muhammadboburshoh** [comment]
Rahmat, to'g'irlaymiz :)

**Comment by Muhammadboburshoh** [comment]
To'girlandi :)
